 
services:
  db:
    image: mysql:8.0
    container_name: mysql-base
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: base
      # MYSQL_USER: appuser
      # MYSQL_PASSWORD: apppass
    ports:
      # Cambia 3307 si se necesita otro puerto
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - db
    environment:
      # Sobrescribe tu spring.datasource.url (ya no localhost)
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/base?serverTimezone=UTC&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sasa
    ports:
      - "8080:8080"

volumes:
  db_data:
